server:  
  port: ${PORT:2222}

spring:  
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://192.168.99.100:33306/hz?useSSL=false
    username: hz
    password: hz123