server:  
  port: ${PORT:2222}

spring:  
  application:
    name: person-service
  datasource:
    url: jdbc:mysql://192.168.99.100:33306/datagrid?useSSL=false
    username: datagrid
    password: datagrid
  logging:
    level:
      com.hazelcast: TRACE
      org.springframework.data.hazelcast: TRACE